### ISSUE TITLE
API definition mismatch

### ISSUE THREAD

**Issue by kgrofelnik** [homanp/superagent-py#9]
I've created an agent using the admin interface and tried using it with the SDK.
It seems there's an entity definition mismatch.

SDK version `0.1.36`

```
Traceback (most recent call last):
  File ".../main.py", line 5, in <module>
    agent = client.agent.get("XXXXXX")
  File ".../lib/python3.10/site-packages/superagent/resources/agent/client.py", line 89, in get
    return pydantic.parse_obj_as(AppModelsResponseAgent, _response.json())  # type: ignore
  File ".../lib/python3.10/site-packages/pydantic/v1/tools.py", line 38, in parse_obj_as
    return model_type(__root__=obj).__root__
  File ".../lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for ParsingModel[AppModelsResponseAgent]
__root__ -> data -> llms -> 0 -> llm -> options
```

**Comment by homanp** [comment]
Did you add an llm to the agent? @kgrofelnik

**Comment by homanp** [comment]
This works for me: 
```
response = client.agent.invoke(
    agent_id="XXXX",
    input="Hi, there",
    enable_streaming=False
)
print(response.data.get("output"))
```

**Comment by kgrofelnik** [comment]
I didn't add an llm using the SDK, but I set the model throught the admin page:
<img width="466" alt="image" src="https://github.com/homanp/superagent-py/assets/3512236/37a71a7f-9d3d-41a7-9f42-21e21fc5dbf0">

**Comment by homanp** [comment]
@kgrofelnik thank u! Debugging.

**Comment by homanp** [comment]
What sdk function are you running? `client.agent.get`?

**Comment by homanp** [comment]
@kgrofelnik should also be fixed in the latest release of the SDK.
